apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: default
type: Opaque
data:
  DB_USERNAME: YWRtaW4=  # base64-encoded 'admin'
  DB_PASSWORD: cGFzc3dvcmQ=  # base64-encoded 'password'

