apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .Chart.Name }}
  namespace: default
spec:
  host: {{ .Chart.Name }}
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
