apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: devopsgpt-policy
  namespace: default
spec:
  selector:
    matchLabels:
      app: devopsgpt
  action: ALLOW
  rules:
    - from:
        - source:
            ipBlocks: ["192.168.1.0/24"] # Specify the IP range allowed to access the service
