apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: devopsgpt-destinationrule
  namespace: default
spec:
  host: devopsgpt
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
