replicaCount: 1

image:
  repository: myrepo
  tag: "latest"
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
