replicaCount: 1

image:
  repository: myrepo
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
secrets:
  dbPassword: cGFzc3dvcmQ=
istio:
  ipBlocks: ["192.168.1.0/24"]

ingress:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
