replicaCount: 1

image:
  repository: myrepo
  tag: "latest"
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
istio:
  ipBlocks: ["192.168.1.0/24"]

ingress:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
